apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component2dsfdf344232d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component23asdfs3322d
    app.kubernetes.io/part-of: test-app
  name: test-component2dsfdf344232d
  namespace: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component2dsfdf344232d
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component2dsfdf344232d
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:test2-test-component2dsfdf344232d
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
